accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('password_change/', views.password_change, name='password_change'),
    path('edit/', views.profile_edit, name="profile_edit"),
]

"""
login_required라는 장식자를 적용하면 /accounts/login/ 주소로 이동하는데
그 이유는 django/conf/global_settings.py의 LOGIN_URL설정이 '/accounts/login/'이기 때문이다.
"""

buy/urls.py
from django.urls import path
from . import views

app_name = 'buy'

urlpatterns =[
    path('order/', views.order, name="order"),
    path('detail/', views.order_detail, name="order_detail"),
    path('discard/', views.order_discard, name="order_discard"),
    path('recommends/', views.recommends, name="recommends"),
]

gstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'),namespace='accounts')),
    path('buy/', include(('buy.urls','buy'), namespace='buy')),
    path('',login_required(TemplateView.as_view(template_name="root.html")), name='root'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# path('accounts/', include('accounts.urls'))

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator, RegexValidator


# Create your models here.
class User(AbstractUser):
    class GenderChoices(models.TextChoices):
        MALE = "M", "남성"
        FEMALE = "F", "여성"
    gender = models.CharField(max_length=1,
                            choices=GenderChoices.choices)

    phone_number = models.CharField(max_length=13,
                                    validators=[RegexValidator(r"^010-?[1-9]\d{3}-?\d{4}$")])
    
    # 20세 미만은 가입불가.
    age = models.CharField(max_length=2,
                            validators=[RegexValidator(r"^[2-9][0-9]$")])

    address = models.CharField(max_length=50, blank=True)
    
    bank = models.CharField(max_length=10, blank=True)
    card = models.CharField(max_length=30, blank=True)

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm as AuthPasswordChangeForm


#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 SignupForm 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
# from django.contrib.auth import get_user_model
# User = get_user_model()
# user = User.objects.first()
# user => <User: gilbert>

# user.password = '1234' 그대로 반환
# user.set_password('1234') 암호화 되서 반환

# UserCreationForm에서 회원가입이 구현되어있다.
class SignupForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # 필수 입력란 
        self.fields['username'].required = True
        self.fields['gender'].required = True
        self.fields['age'].required = True
        self.fields['phone_number'].required = True
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True


    class Meta(UserCreationForm.Meta):
        model  = User
        fields = ['username','gender','age','phone_number','email', 'first_name', 'last_name']

    # 이미 있는 email에 대한 확인
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            qs = User.objects.filter(email=email)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 이메일 주소입니다.")
        return email



#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 ProfileForm 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields =  ['address','phone_number','email']



#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 PasswordChangeForm 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
class PasswordChangeForm(AuthPasswordChangeForm):
    def clean_new_password2(self):

        # 기존 비밀번호 가져오기.
        old_password = self.cleaned_data.get('old_password')
        
        # 부모 클래스(SetPasswordForm)에서 clean_new_password2 사용.
        # clean_new_password2()에서 new_password1 and new_password2검사
        new_password2 = super().clean_new_password2()
        if old_password == new_password2:
            raise forms.ValidationError(
                "이전과 동일한 암호 입니다."
            )
        return new_password2 

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import SignupForm, ProfileForm,PasswordChangeForm
from django.contrib.auth.views import (
    LoginView,
    PasswordChangeView as AuthPasswordChangeView)
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 회원가입 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            signed_user = form.save()
            auth_login(request, signed_user)
            messages.success(request,"회원가입을 환영합니다.")
            next_url = request.GET.get('next','/')
            return redirect(next_url)
    else:
        form = SignupForm()
    context = {'form':form}
    return render(request,'accounts/signup_form.html', context)



#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 로그인 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
# 사실 loginview는 django.auth에 구현이 되어있다. 
# def login(request):
#     pass
# 별도의 logic이 필요한 경우 위와 같이 함수기반 view로 구현 
# 아니면 class기반으로 할 수 있다.

login = LoginView.as_view(template_name ="accounts/login_form.html")



#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 로그아웃 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
# logout = LogoutView.as_view(template_name="accounts/logout_form.html")
# def logout(request):
#     messages.success(request, "로그아웃 되었습니다.")
#     return logout_then_login(request)
logout = auth_views.LogoutView.as_view()



#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 프로필 수정 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
@login_required
def profile_edit(request):
    if request.method == "POST":    
        # 기존에 저장되어 있는 프로필 가져오기.
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request,"프로필을 수정했습니다.")
            return redirect("root")
    else:
        form = ProfileForm(instance=request.user)
    return render(request,'accounts/profile_edit_form.html',{'form':form})



#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 비밀번호 수정 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#

class PasswordChangeView(LoginRequiredMixin, AuthPasswordChangeView):
    form_class = PasswordChangeForm

    """
    파이썬은 인터프리터 언어이기 때문에 한줄 한줄 실행한다.
    근데 비밀번호 변경은 필요시에만 실행되어야 한다.
    따라서 reverse_lazy를 사용하여, 해당변수에 직접 접근 혹은
    메서드가 호출될 때 실행시켜야 한다.
    """
    success_url = reverse_lazy('password_change')
    template_name = 'accounts/password_change_form.html'

    def form_valid(self,form):
        messages.success(self.request,"암호를 변경했습니다.")
        return super().form_valid(form)

password_change = PasswordChangeView.as_view()

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="로그인" submit_label="로그인" %}
                <a href="{% url 'accounts:signup' %}"class="btn btn-primary ">
                    회원가입
                </a>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends 'accounts/layout.html' %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="암호변경" submit_label="암호변경" %}
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_edit_form.html
{% extends "accounts/layout.html" %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal">Profile Edit</h1>
        <p class="fs-5 text-muted">프로필 수정</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="프로필 수정" submit_label="프로필 수정" %}
                <a href="{% url 'accounts:password_change' %}"class="btn btn-primary ">
                    비밀번호 수정
                </a>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="회원가입" submit_label="회원가입" %}
            </div>
        </div>
    </div>
{% endblock %}