accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('password_change/', views.password_change, name='password_change'),
    path('edit/', views.profile_edit, name="profile_edit"),
]

"""
login_required라는 장식자를 적용하면 /accounts/login/ 주소로 이동하는데
그 이유는 django/conf/global_settings.py의 LOGIN_URL설정이 '/accounts/login/'이기 때문이다.
"""

buy/urls.py
from django.urls import path
from . import views

app_name = 'buy'

urlpatterns =[
    path('order/', views.order, name="order"),
    path('detail/', views.order_detail, name="order_detail"),
    path('discard/', views.order_discard, name="order_discard"),
    path('recommends/', views.recommends, name="recommends"),
]

gstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'),namespace='accounts')),
    path('buy/', include(('buy.urls','buy'), namespace='buy')),
    path('',login_required(TemplateView.as_view(template_name="root.html")), name='root'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# path('accounts/', include('accounts.urls'))

gstore/templates/_form.html
{% load bootstrap4 %}

<div class="card">
    {% if form_title %}
        <div class="card-header">
            {{ form_title }}
        </div>
    {% endif %}
    <div class="card-body">
        {% if form %}
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {{ submit_label|default:"Submit" }}
                    </button>
                {% endbuttons %}
            </form>
        {% else %}
            <div class="alert alert-danger">
                form 객체를 지정해주세요.
            </div>
        {% endif %}

    </div>
</div>

gstore/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="#">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gstore</title>

    <link rel="stylesheet" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}"/>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.min.js' %}"></script>



</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" >
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <header>
                    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
                        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg> -->
                        <img style="width:10%" class="img-responsive img-rounded " src="http://images.gofreedownload.net/letter-g-32995.jpg">
                        <span class="fs-4">-STORE</span>
                        </a>

                        {% if user.is_authenticated %}
                        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'buy:order' %}">주문📑</a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'buy:order_detail' %}">주문 조회🛵</a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="#">게시판📌</a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'buy:recommends' %}">혼술과 영화🎬</a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'accounts:profile_edit' %}">
                                    {{ user.username }}😀
                            </a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'accounts:logout' %}">
                                로그아웃❌
                            </a>
                        {% endif %}
                        </nav>
                    </div>

                </header>
            </div>
        </div>
    </div>

    {% block content %}
    {% endblock %}
</body>
</html>

gstore/templates/root.html
{% extends "layout.html" %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal">🙉Gstore에 오신것을 환영합니다🙉 </h1>
        <p class="fs-5 text-muted">오늘 하루 스트레스를 술과 함께 날려주세요~</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
            </div>
        </div>
    </div>
{% endblock %}