buy/urls.py
from django.urls import path
from . import views

app_name = 'buy'

urlpatterns =[
    path('order/', views.order, name="order"),
    path('detail/', views.order_detail, name="order_detail"),
    path('discard/', views.order_discard, name="order_discard"),
    path('recommends/', views.recommends, name="recommends"),
]

gstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'),namespace='accounts')),
    path('buy/', include(('buy.urls','buy'), namespace='buy')),
    path('',login_required(TemplateView.as_view(template_name="root.html")), name='root'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# path('accounts/', include('accounts.urls'))

buy/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator,RegexValidator

#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 Product 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
class Product(models.Model):
    name = models.CharField(max_length=10)
    price = models.IntegerField()
    alchol = models.DecimalField(max_digits=4, decimal_places=2)
    description = models.TextField()  
    place = models.CharField(max_length=10)

    def __str__(self):
        return self.name


#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 Order 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    products = models.ForeignKey(Product,on_delete=CASCADE, related_name='order_product')
    product_count = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(3)])
    order_time = models.DateTimeField(auto_now_add=True)
    address =  models.CharField(max_length=150)

    class Meta:
        ordering = ['-id']


#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 Movie 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#

class Movie(models.Model):
    title =models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

buy/forms.py
from django import forms
# from django.forms import widgets
from .models import Order, Movie

class OrderForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['product_count'].required = True
        self.fields['address'].required = True

    class Meta:
        model = Order
        fields = ['products','product_count','address']

class MovieForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['title'].required = True

    class Meta:
        model = Movie
        fields = ['title']

buy/views.py
from django.shortcuts import render,redirect
from .forms import OrderForm, MovieForm
from django.utils import timezone
from django.contrib import messages
from .models import Order, Movie
from django.contrib.auth.decorators import login_required
from .modeling import get_recommendations, overviews
import pandas as pd
# import pickle
#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 주문 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#

@login_required
def order(request):
    if request.method=='POST':
        form = OrderForm(request.POST)
        if form.is_valid():
                ordering = form.save(commit=False)
                ordering.order_time = timezone.now()
                ordering.user = request.user
                ordering.save()
                messages.success(request,"주문을 성공하셨습니다")
                return redirect('buy:recommends')
    else:
        form = OrderForm()
    
    context = {'form':form}
    return render(request,"buy/order_form.html",context)

#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 주문 내역 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#
@login_required
def order_detail(request):
    # request.user의 주문 목록 모두 가져오기.
    order_list = Order.objects.filter(user=request.user)
    context = {'order_list':order_list}
    return render(request,'buy/order_detail.html',context)


# @login_required
# def order_change(request):
#     if request.method =="POST":
#         form = OrderForm(request.POST, instance=request.user)
#         if form.is_valid():
#             ordering = form.save(commit=False)
#             ordering.order_time = timezone.now()
#             # ordering.user = request.user
#             ordering.save()
#     else:
#         form = OrderForm(instance=request.user)

    # context = {'form':form}
    # return render(request,"buy/order_form.html",context)

#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 주문 취소 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#

@login_required
def order_discard(request):
    order = Order.objects.filter(user_id=request.user.id)
    order.delete()
    messages.success(request,"주문을 취소했습니다.")
    return redirect("root")



#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 추천2 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#

@login_required
def recommends(request):
    if request.method == "POST":
        Movies = Movie.objects.all().filter(user=request.user)
        if len(Movies) >= 1:
            Movies.delete()
        else:
            pass
        form = MovieForm(request.POST)
        if form.is_valid:
            m = form.save(commit=False)
            m.user = request.user
            m.save()
            return redirect('buy:recommends')

    form = MovieForm()
    movies = Movie.objects.last() 
    # pickle사용
    # with open('get_recommendations', 'rb') as f:
    #     recommendation = pickle.load(f) 

    try:
        # pred = recommendation(movies.title) # pickle사용할 경우
        pred = get_recommendations(movies.title)
        final = pd.DataFrame(pred)

        movies_title = movies.title 
        recommend_mv = final.title
        ove = overviews.loc[movies.title].overview
        release_date = overviews.loc[movies.title].release_date
        runtime = int(overviews.loc[movies.title].runtime)
        vote_average = overviews.loc[movies.title].vote_average
        genres	= overviews.loc[movies.title].genres	

        context = {
            'form':form,
            'movies_title':movies_title,
            'recommend_mv':recommend_mv,
            'ove':ove,
            'release_date':release_date,
            'runtime':runtime,
            'vote_average':vote_average,
            'genres':genres
        }

        return render(request, 'buy/movie_test.html',context)

    except:
        context = {
            'form':form,
        }

        return render(request, 'buy/movie_main.html',context)

#〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓 Weather API 〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓#

# @login_required
# def recommend(request):
#     if request.method == "POST":
#         cities = City.objects.all().filter(user=request.user)
#         if len(cities) >= 1:
#             cities.delete()
#         else:
#             pass
#         form = CityForm(request.POST)
#         if form.is_valid:       
#             k = form.save(commit=False)
#             k.user = request.user
#             k.save()
#             return redirect("buy:recommend")

#     form = CityForm()

#     cities = City.objects.all().filter(user=request.user)

#     weather_data,comments = [],[]
#     for city in cities:
#         url = f'http://api.openweathermap.org/data/2.5/weather?q={city}&appid=170042f861af86da70b4e4b96749b810&lang=kr'
#         r = requests.get(url).json()
#         print(r)
#         city_weather = {
#             'city' : city.name,
#             'temperature' : round(r['main']['temp']- 273.15,1),
#             'description' : r['weather'][0]['description'],
#             'icon' : r['weather'][0]['icon']
#         }
#         weather_data.append(city_weather)


#         if '흐림' in city_weather['description']:
#             comment = "오늘은 구름이 많이 꼈네요! 집에서 한잔 해야 할것 같아요~"
#             comments.append(comment)
#         elif '맑음' in city_weather['description']:
#             comment = "오늘은 화창하군요~! 친구들과 공원에서 한잔 어때요~?!"
#             comments.append(comment)
#         elif '비' in city_weather['description']:
#             comment = "오늘은 비가오네요ㅠㅠ! 오늘은 전에 막걸리 고고~!"
#             comments.append(comment)
#         elif '구름' in city_weather['description']:
#             comment = "오늘은 구름이 많이 꼈네요! 집에서 한잔 해야 할것 같아요~"
#             comments.append(comment)
#         else:
#             pass

#     # 상품 추천
#     product_list = Product.objects.all()
#     pick = random.choice(product_list)
#     context = {
#                 'product_list':product_list,
#                 'pick':pick,
#                 'weather_data' : weather_data,
#                 'form':form,
#                 'comments' : comments,
#                 }
#     return render(request, 'buy/recommend.html',context)

buy/templates/buy/layout.html
{% extends "layout.html" %}

buy/templates/buy/movie_main.html
{% extends "buy/layout.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>What's the weather like?</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    </head>
    <body>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Movie</h1>
            <p class="fs-5 text-muted">혼술과 함께할 영화는~?</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    {% include "_form.html" with form_title="제목을 입력해주세요!" submit_label="검색하기" %}
                </div>
            </div>
        </div>
    </body>
</html>
{% endblock %}

buy/templates/buy/movie_test.html
{% extends "buy/layout.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>What's the weather like?</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    </head>
    <body>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Movie</h1>
            <p class="fs-5 text-muted">혼술과 함께할 영화는~?</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    {% include "_form.html" with form_title="제목을 입력해주세요!" submit_label="검색하기" %}
                    <br>
                </div>
            </div>
        </div>
        <section class="section">
            <div class="container">
                <div class="columns">
                    <div class="column is-offset-3 is-6">
                        <div class="box">
                            <article class="media">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-sm-20">
                                            검색 영화: {{ movies_title }}
                                            <br>
                                            개봉일: {{ release_date }}
                                            <br>
                                            장르:
                                            {% for i in  genres %}
                                                #{{ i }}
                                            {% endfor %}
                                            <br>
                                            상영시간: {{ runtime }}분
                                            <br>
                                            평점: {{ vote_average }}점
                                        </div>    
                                    </div>
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </div>
        </section>        <section class="section">
            <div class="container">
                <div class="columns">
                    <div class="column is-offset-3 is-6">
                        <div class="box">
                            <article class="media">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-sm-20">
                                            <h2>줄거리</h2>
                                            <br>
                                            {{ ove }}
                                        </div>    
                                    </div>
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% for i in recommend_mv %}
            <section class="section">
                <div class="container">
                    <div class="columns">
                        <div class="column is-offset-3 is-6">
                            <div class="box">
                                <article class="media">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sm-20">
                                                추천 영화 : {{ i }}
                                            </div>    
                                        </div>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        {% endfor %}
    </body>
</html>
{% endblock %}

buy/templates/buy/order_detail.html
{% extends 'buy/layout.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>

<body>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal">Order List</h1>
        <p class="fs-5 text-muted">주문 리스트</p>
    </div>
    {% for i in order_list %}
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-3 is-6">
                    <div class="box">
                        <article class="media">
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm-10">
                                            - 상품명 : {{i.products}}<br>
                                            - 상품 가격 : {{i.products.price}}<br>
                                            - 상품 갯수 : {{i.product_count}}<br>
                                            - 주문 시간 : {{i.order_time}}<br>
                                            - 주소 : {{i.address}}<br>
                                            <br>
                                            <a href="{% url 'buy:order_discard' %}">❌주문 취소 하기❌</a> << 취소 후 다시 주문해주세요!
                                            <br>
                                    </div>    
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}
<body>
{% endblock %}

buy/templates/buy/order_form.html
{% extends "buy/layout.html" %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal">Order</h1>
        <p class="fs-5 text-muted">주문</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="구매하기" submit_label="구매하기" %}
            </div>
        </div>
    </div>
{% endblock %}